Adding missing, updating outdated functions
aoijs/documentation pull request #122
Opened 2022-06-05 18:29 UTC by NeoAIChan

I'll be updating function files day-by-day.

2022-06-05 18:33 UTC, NeoAIChan commented
Deleted $complexCooldown on the summary, and added $advanceCooldown.

2022-06-08 10:33 UTC, Leref approved these changes

2022-06-09 09:22 UTC, NeoAIChan commented
$if function slightly got better details for bot developers understand it.

2022-06-09 13:20 UTC, NeoAIChan commented
Cause of using an app to "push", it sends two commits sometimes. Don't mind it.

2022-06-09 17:26 UTC, Leref requested changes
Please fix this accordingly.

2022-06-09 17:26 UTC, Leref commented on src/functions/usdcreateapplicationcommand.md
> -$createApplicationCommand[guildID/global;application name;application description?;default permission;type;options?]
Revert this.
It should be guildID or global.

2022-06-09 17:26 UTC, Leref commented on src/functions/usddeleteapplicationcommand.md
> +$deleteApplicationCommand[location;application id]
Should be guildID or global in location.

2022-06-09 17:26 UTC, Leref commented on src/functions/usdgetapplicationcommandid.md
> +$getApplicationCommand[application name;location]
Incorrect usage name, it's missing `id` -> `$getApplicationCommandID`

2022-06-09 17:43 UTC, Leref approved these changes

2022-06-09 17:46 UTC, merged