Updating Functions
aoijs/documentation pull request #130
Opened 2022-06-12 09:50 UTC by NeoAIChan

2022-06-12 10:32 UTC, NeoAIChan commented
The app has issues with merging, it has been fixed on `a42bccb`.

2022-06-13 10:11 UTC, Leref requested changes

2022-06-13 10:11 UTC, Leref commented on src/functions/usdvolume.md
> +> P.S. : I hope you're not thinking about earrape...
This isn't needed.

2022-06-14 10:19 UTC, Leref requested changes

2022-06-14 10:19 UTC, Leref commented on src/functions/usdvanityuses.md
> +$vanityUses[guild id?]
guildID proper.

2022-06-14 10:19 UTC, Leref commented on src/functions/usdvoiceid.md
> +$voiceID[user id?]
userID proper.

2022-06-14 10:40 UTC, Leref approved these changes

2022-06-14 10:40 UTC, merged