Adding Missing and Updating: Functions
aoijs/documentation pull request #132
Opened 2022-06-14 11:31 UTC by NeoAIChan

It will be ready sooner.

2022-06-14 21:41 UTC, NeoAIChan reviewed
It looks great to me, I feel tired cause of lacking of sleep. Let me know, if something needs to be fixed.

2022-06-18 07:50 UTC, USERSATOSHI requested changes

2022-06-18 07:50 UTC, USERSATOSHI commented on src/functions/usduserrolecount.md
> +  $username has $userRoleCount roles!
it's $userRolesCount

2022-06-18 07:50 UTC, USERSATOSHI commented on src/functions/usduserroles.md
> +  Your Roles: $userRoles[$authorID;$guildID;name;,]
change name to id

cause $userRoles returns `@everyone` for name

2022-06-18 07:50 UTC, USERSATOSHI commented on src/functions/usdusersbanned.md
> +  $usersBanned[$guildID;yes;name;, ]
change name to username

2022-06-18 07:50 UTC, USERSATOSHI commented on src/functions/usduserswithrole.md
> +  $usersWithRole[$roleID[Profossional];697039582922801182;nickname;, ]
change nickname to displayName

2022-06-18 10:33 UTC, NeoAIChan commented on src/functions/usduserrolecount.md
> +  $username has $userRoleCount roles!
Fixed.

2022-06-18 11:41 UTC, USERSATOSHI approved these changes
LGTM

2022-06-18 11:41 UTC, merged