Updating functions, fixing typos~
aoijs/documentation pull request #136
Opened 2022-07-14 05:59 UTC by NeoAIChan

2022-07-17 21:39 UTC, NeoAIChan commented
@USERSATOSHI & @Leref, prioritized the functions needed to update. Ready to merge.

2022-07-18 05:00 UTC, NeoAIChan commented
Will be updating summary.md along with array functions

2022-07-19 06:13 UTC, NeoAIChan commented
@Leref

2022-07-19 06:46 UTC, USERSATOSHI requested changes

2022-07-19 06:46 UTC, USERSATOSHI commented on src/functions/usdisautocomplete.md
> +`$isAutoComplete` is used to check it is auto-complete or not.
not specific enough here

2022-07-19 09:13 UTC, USERSATOSHI requested changes

2022-07-19 09:13 UTC, USERSATOSHI commented on src/functions/usdisautocomplete.md
> +`$isAutoComplete` is used to checking the if interaction command's *interaction autocomplete* feature enabled or disabled.
make it 
> check if interaction command is an *autocompleteInteraction*

2022-07-21 12:30 UTC, Leref approved these changes

2022-07-21 12:30 UTC, merged