Create usdaddselectmenu.md
aoijs/documentation pull request #81
Opened 2021-12-10 05:20 UTC by Bumblebee-3

totally weird

2022-05-03 12:21 UTC, NeoAIChan requested changes
Those are needs to be changed @Leref

2022-05-03 12:21 UTC, NeoAIChan commented on src/functions/usdaddselectmenu.md
> +`$interactionData[message.id]` => the message id to which the button has attached.
button for select menu?

2022-05-03 12:21 UTC, NeoAIChan commented on src/functions/usdaddselectmenu.md
> +`$interactionData[author.id]` => The person who clicked the button.
Those are needs to be changed to menu though.

2022-05-03 12:21 UTC, NeoAIChan commented on src/functions/usdaddselectmenu.md
> +`$interactionData[channel.id]` => The channel in which the button is located.
And this one @Bumblebee-3

2022-06-01 13:15 UTC, Bumblebee-3 commented on src/functions/usdaddselectmenu.md
> +`$interactionData[channel.id]` => The channel in which the button is located.
Heyyy, Sorry, didnt notice that...

2022-06-01 13:15 UTC, Bumblebee-3 commented on src/functions/usdaddselectmenu.md
> +`$interactionData[channel.id]` => The channel in which the button is located.
I just fixed it

2022-06-07 23:09 UTC, Leref commented
Conflicts and already updated.

2022-06-07 23:09 UTC, closed without merging